### PR TITLE
Feature/cloudwatch

### PR DESCRIPTION
**Pull request by fvazquez-caylent**
Adds a new example called minimal-logs.
Adds two variables ingress_protocol and egress_protocol to align to the lates security group release.
Updates CHANGELOG file.

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by fvazquez-caylent** [comment]
Closing for now.

**Pull request closed without merging**
