### PR TITLE
DEV-14729 & DEV-14295 - Updates minimum terraform and provider versions

### PR DESCRIPTION
**Pull request by souza-dan**
https://datatamr.atlassian.net/browse/DEV-14729
https://datatamr.atlassian.net/browse/DEV-14295

Ran plan for the example, but not apply:
```
var.ami_id
  AMI to use for Tamr EC2 instance

  Enter a value: foo

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.hbase-logs-bucket.module.bucket-iam-policy.data.aws_iam_policy_document.rw_source_policy_doc[0]: Refreshing state...
module.spark-logs-bucket.module.bucket-iam-policy.data.aws_iam_policy_document.rw_source_policy_doc[0]: Refreshing state...
module.tamr-vm.module.aws-iam-policies.data.aws_caller_identity.current: Refreshing state...
module.tamr-vm.module.aws-iam-role.data.aws_iam_policy_document.instance-assume-role-policy: Refreshing state...
module.hbase-rootdir-bucket.module.bucket-iam-policy.data.aws_iam_policy_document.rw_source_policy_doc[0]: Refreshing state...
module.hbase-logs-bucket.module.bucket-iam-policy.data.aws_iam_policy_document.path_specific_rw_doc[0]: Refreshing state...
module.spark-logs-bucket.module.bucket-iam-policy.data.aws_iam_policy_document.path_specific_rw_doc[0]: Refreshing state...
module.hbase-rootdir-bucket.module.bucket-iam-policy.data.aws_iam_policy_document.path_specific_rw_doc[0]: Refreshing state...
module.tamr-vm.module.aws-iam-policies.data.aws_iam_policy_document.emr_creator_policy: Refreshing state...

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.aws_s3_bucket_object.bootstrap_script will be read during apply
  # (config refers to values not yet known)
 <= data "aws_s3_bucket_object" "bootstrap_script"  {
      + body                          = (known after apply)
      + bucket                        = (known after apply)
      + bucket_key_enabled            = (known after apply)
      + cache_control                 = (known after apply)
      + content_disposition           = (known after apply)
      + content_encoding              = (known after apply)
      + content_language              = (known after apply)
      + content_length                = (known after apply)
      + content_type                  = (known after apply)
      + etag                          = (known after apply)
      + expiration                    = (known after apply)
      + expires                       = (known after apply)
      + id                            = (known after apply)
      + key                           = (known after apply)
      + last_modified                 = (known after apply)
      + metadata                      = (known after apply)
      + object_lock_legal_hold_status = (known after apply)
      + object_lock_mode              = (known after apply)
      + object_lock_retain_until_date = (known after apply)
      + server_side_encryption        = (known after apply)
      + sse_kms_key_id                = (known after apply)
      + storage_class                 = (known after apply)
      + tags                          = (known after apply)
      + version_id                    = (known after apply)
      + website_redirect_location     = (known after apply)
    }

  # data.aws_s3_bucket_object.bootstrap_script_2 will be read during apply
  # (config refers to values not yet known)
 <= data "aws_s3_bucket_object" "bootstrap_script_2"  {
      + body                          = (known after apply)
      + bucket                        = (known after apply)
      + bucket_key_enabled            = (known after apply)
      + cache_control                 = (known after apply)
      + content_disposition           = (known after apply)
      + content_encoding              = (known after apply)
      + content_language              = (known after apply)
      + content_length                = (known after apply)
      + content_type                  = (known after apply)
      + etag                          = (known after apply)
      + expiration                    = (known after apply)
      + expires                       = (known after apply)
      + id                            = (known after apply)
      + key                           = (known after apply)
      + last_modified                 = (known after apply)
      + metadata                      = (known after apply)
      + object_lock_legal_hold_status = (known after apply)
      + object_lock_mode              = (known after apply)
      + object_lock_retain_until_date = (known after apply)
      + server_side_encryption        = (known after apply)
      + sse_kms_key_id                = (known after apply)
      + storage_class                 = (known after apply)
      + tags                          = (known after apply)
      + version_id                    = (known after apply)
      + website_redirect_location     = (known after apply)
    }

  # aws_s3_bucket_object.check_pip_install_script will be created
  + resource "aws_s3_bucket_object" "check_pip_install_script" {
      + acl                    = "private"
      + bucket                 = (known after apply)
      + bucket_key_enabled     = (known after apply)
      + content_type           = "text/x-shellscript"
      + etag                   = (known after apply)
      + force_destroy          = false
      + id                     = (known after apply)
      + key                    = "bootstrap-script-tamr-vm/check-install.sh"
      + kms_key_id             = (known after apply)
      + server_side_encryption = "AES256"
      + source                 = "./test-bootstrap-scripts/check-install.sh"
      + storage_class          = (known after apply)
      + version_id             = (known after apply)
    }

  # aws_s3_bucket_object.install_pip_bootstrap_script will be created
  + resource "aws_s3_bucket_object" "install_pip_bootstrap_script" {
      + acl                    = "private"
      + bucket                 = (known after apply)
      + bucket_key_enabled     = (known after apply)
      + content_type           = "text/x-shellscript"
      + etag                   = (known after apply)
      + force_destroy          = false
      + id                     = (known after apply)
      + key                    = "bootstrap-script-tamr-vm/install-pip.sh"
      + kms_key_id             = (known after apply)
      + server_side_encryption = "AES256"
      + source                 = "./test-bootstrap-scripts/install-pip.sh"
      + storage_class          = (known after apply)
      + version_id             = (known after apply)
    }

  # aws_subnet.tamr_vm_subnet will be created
  + resource "aws_subnet" "tamr_vm_subnet" {
      + arn                             = (known after apply)
      + assign_ipv6_address_on_creation = false
      + availability_zone               = "us-east-1e"
      + availability_zone_id            = (known after apply)
      + cidr_block                      = "1.2.3.0/24"
      + id                              = (known after apply)
      + ipv6_cidr_block_association_id  = (known after apply)
      + map_public_ip_on_launch         = false
      + owner_id                        = (known after apply)
      + tags_all                        = (known after apply)
      + vpc_id                          = (known after apply)
    }

  # aws_vpc.tamr_vm_vpc will be created
  + resource "aws_vpc" "tamr_vm_vpc" {
      + arn                              = (known after apply)
      + assign_generated_ipv6_cidr_block = false
      + cidr_block                       = "1.2.3.0/24"
      + default_network_acl_id           = (known after apply)
      + default_route_table_id           = (known after apply)
      + default_security_group_id        = (known after apply)
      + dhcp_options_id                  = (known after apply)
      + enable_classiclink               = (known after apply)
      + enable_classiclink_dns_support   = (known after apply)
      + enable_dns_hostnames             = (known after apply)
      + enable_dns_support               = true
      + id                               = (known after apply)
      + instance_tenancy                 = "default"
      + ipv6_association_id              = (known after apply)
      + ipv6_cidr_block                  = (known after apply)
      + main_route_table_id              = (known after apply)
      + owner_id                         = (known after apply)
      + tags_all                         = (known after apply)
    }

  # tls_private_key.tamr_ec2_private_key will be created
  + resource "tls_private_key" "tamr_ec2_private_key" {
      + algorithm                  = "RSA"
      + ecdsa_curve                = "P224"
      + id                         = (known after apply)
      + private_key_pem            = (sensitive value)
      + public_key_fingerprint_md5 = (known after apply)
      + public_key_openssh         = (known after apply)
      + public_key_pem             = (known after apply)
      + rsa_bits                   = 2048
    }

  # module.tamr_ec2_key_pair.aws_key_pair.this[0] will be created
  + resource "aws_key_pair" "this" {
      + arn         = (known after apply)
      + fingerprint = (known after apply)
      + id          = (known after apply)
      + key_name    = "tamr-ec2-test-key"
      + key_pair_id = (known after apply)
      + public_key  = (known after apply)
    }

  # module.hbase-logs-bucket.module.bucket-iam-policy.aws_iam_policy.rw_policy[0] will be created
  + resource "aws_iam_policy" "rw_policy" {
      + arn       = (known after apply)
      + id        = (known after apply)
      + name      = "test-hbase-logs-bucket-read-write"
      + path      = "/"
      + policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "s3:PutObject",
                          + "s3:ListObjects",
                          + "s3:ListBucket",
                          + "s3:HeadBucket",
                          + "s3:GetObject",
                          + "s3:DeleteObject",
                          + "s3:CreateJob",
                          + "s3:AbortMultipartUpload",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:s3:::test-hbase-logs-bucket/*",
                          + "arn:aws:s3:::test-hbase-logs-bucket",
                        ]
                      + Sid      = "ReadWritePolicy0"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id = (known after apply)
    }

  # module.hbase-logs-bucket.module.encrypted-bucket.aws_s3_bucket.new_bucket will be created
  + resource "aws_s3_bucket" "new_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-hbase-logs-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = true
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + server_side_encryption_configuration {
          + rule {
              + apply_server_side_encryption_by_default {
                  + sse_algorithm = "AES256"
                }
            }
        }

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

  # module.hbase-logs-bucket.module.encrypted-bucket.aws_s3_bucket_policy.sse_bucket_policy will be created
  + resource "aws_s3_bucket_policy" "sse_bucket_policy" {
      + bucket = (known after apply)
      + id     = (known after apply)
      + policy = (known after apply)
    }

  # module.hbase-rootdir-bucket.module.bucket-iam-policy.aws_iam_policy.rw_policy[0] will be created
  + resource "aws_iam_policy" "rw_policy" {
      + arn       = (known after apply)
      + id        = (known after apply)
      + name      = "test-hbase-root-directory-bucket-read-write"
      + path      = "/"
      + policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "s3:PutObject",
                          + "s3:ListObjects",
                          + "s3:ListBucket",
                          + "s3:HeadBucket",
                          + "s3:GetObject",
                          + "s3:DeleteObject",
                          + "s3:CreateJob",
                          + "s3:AbortMultipartUpload",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:s3:::test-hbase-root-directory-bucket/*",
                          + "arn:aws:s3:::test-hbase-root-directory-bucket",
                        ]
                      + Sid      = "ReadWritePolicy0"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id = (known after apply)
    }

  # module.hbase-rootdir-bucket.module.encrypted-bucket.aws_s3_bucket.new_bucket will be created
  + resource "aws_s3_bucket" "new_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-hbase-root-directory-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = true
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + server_side_encryption_configuration {
          + rule {
              + apply_server_side_encryption_by_default {
                  + sse_algorithm = "AES256"
                }
            }
        }

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

  # module.hbase-rootdir-bucket.module.encrypted-bucket.aws_s3_bucket_policy.sse_bucket_policy will be created
  + resource "aws_s3_bucket_policy" "sse_bucket_policy" {
      + bucket = (known after apply)
      + id     = (known after apply)
      + policy = (known after apply)
    }

  # module.spark-logs-bucket.module.bucket-iam-policy.aws_iam_policy.rw_policy[0] will be created
  + resource "aws_iam_policy" "rw_policy" {
      + arn       = (known after apply)
      + id        = (known after apply)
      + name      = "test-spark-logs-bucket-read-write"
      + path      = "/"
      + policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "s3:PutObject",
                          + "s3:ListObjects",
                          + "s3:ListBucket",
                          + "s3:HeadBucket",
                          + "s3:GetObject",
                          + "s3:DeleteObject",
                          + "s3:CreateJob",
                          + "s3:AbortMultipartUpload",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:s3:::test-spark-logs-bucket/*",
                          + "arn:aws:s3:::test-spark-logs-bucket",
                        ]
                      + Sid      = "ReadWritePolicy0"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id = (known after apply)
    }

  # module.spark-logs-bucket.module.encrypted-bucket.aws_s3_bucket.new_bucket will be created
  + resource "aws_s3_bucket" "new_bucket" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "test-spark-logs-bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = true
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + server_side_encryption_configuration {
          + rule {
              + apply_server_side_encryption_by_default {
                  + sse_algorithm = "AES256"
                }
            }
        }

      + versioning {
          + enabled    = (known after apply)
          + mfa_delete = (known after apply)
        }
    }

  # module.spark-logs-bucket.module.encrypted-bucket.aws_s3_bucket_policy.sse_bucket_policy will be created
  + resource "aws_s3_bucket_policy" "sse_bucket_policy" {
      + bucket = (known after apply)
      + id     = (known after apply)
      + policy = (known after apply)
    }

  # module.tamr-vm.module.aws-iam-policies.aws_iam_policy.emr_creator_minimal_policy will be created
  + resource "aws_iam_policy" "emr_creator_minimal_policy" {
      + arn       = (known after apply)
      + id        = (known after apply)
      + name      = "TestEmrCreatorPolicy"
      + path      = "/"
      + policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = [
                          + "iam:PassRole",
                          + "elasticmapreduce:TerminateJobFlows",
                          + "elasticmapreduce:ListSteps",
                          + "elasticmapreduce:ListInstances",
                          + "elasticmapreduce:ListInstanceGroups",
                          + "elasticmapreduce:ListBootstrapActions",
                          + "elasticmapreduce:AddJobFlowSteps",
                          + "elasticmapreduce:AddInstanceGroups",
                        ]
                      + Effect   = "Allow"
                      + Resource = [
                          + "arn:aws:iam::825693534638:role/*",
                          + "arn:aws:elasticmapreduce:*:825693534638:cluster/*",
                        ]
                      + Sid      = ""
                    },
                  + {
                      + Action   = "elasticmapreduce:RunJobFlow"
                      + Effect   = "Allow"
                      + Resource = "arn:aws:elasticmapreduce:*"
                      + Sid      = ""
                    },
                  + {
                      + Action   = [
                          + "elasticmapreduce:ListClusters",
                          + "elasticmapreduce:Describe*",
                        ]
                      + Effect   = "Allow"
                      + Resource = "*"
                      + Sid      = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + policy_id = (known after apply)
    }

  # module.tamr-vm.module.aws-iam-policies.aws_iam_role_policy_attachment.emr_creator_policy_attachment will be created
  + resource "aws_iam_role_policy_attachment" "emr_creator_policy_attachment" {
      + id         = (known after apply)
      + policy_arn = (known after apply)
      + role       = (known after apply)
    }

  # module.tamr-vm.module.aws-iam-policies.aws_iam_role_policy_attachment.emrfs_user_s3_policy[0] will be created
  + resource "aws_iam_role_policy_attachment" "emrfs_user_s3_policy" {
      + id         = (known after apply)
      + policy_arn = (known after apply)
      + role       = (known after apply)
    }

  # module.tamr-vm.module.aws-iam-policies.aws_iam_role_policy_attachment.emrfs_user_s3_policy[1] will be created
  + resource "aws_iam_role_policy_attachment" "emrfs_user_s3_policy" {
      + id         = (known after apply)
      + policy_arn = (known after apply)
      + role       = (known after apply)
    }

  # module.tamr-vm.module.aws-iam-policies.aws_iam_role_policy_attachment.emrfs_user_s3_policy[2] will be created
  + resource "aws_iam_role_policy_attachment" "emrfs_user_s3_policy" {
      + id         = (known after apply)
      + policy_arn = (known after apply)
      + role       = (known after apply)
    }

  # module.tamr-vm.module.aws-iam-role.aws_iam_instance_profile.tamr_user_instance_profile will be created
  + resource "aws_iam_instance_profile" "tamr_user_instance_profile" {
      + arn         = (known after apply)
      + create_date = (known after apply)
      + id          = (known after apply)
      + name        = "test-tamr-ec2-instance-profile"
      + path        = "/"
      + role        = "test-tamr-ec2-role"
      + unique_id   = (known after apply)
    }

  # module.tamr-vm.module.aws-iam-role.aws_iam_role.tamr_user_iam_role will be created
  + resource "aws_iam_role" "tamr_user_iam_role" {
      + arn                   = (known after apply)
      + assume_role_policy    = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = "sts:AssumeRole"
                      + Effect    = "Allow"
                      + Principal = {
                          + Service = "ec2.amazonaws.com"
                        }
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + managed_policy_arns   = (known after apply)
      + max_session_duration  = 3600
      + name                  = "test-tamr-ec2-role"
      + path                  = "/"
      + unique_id             = (known after apply)

      + inline_policy {
          + name   = (known after apply)
          + policy = (known after apply)
        }
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group.tamr-vm-sg will be created
  + resource "aws_security_group" "tamr-vm-sg" {
      + arn                    = (known after apply)
      + description            = "Default security group for tamr"
      + egress                 = (known after apply)
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "tamr-instance-security-group"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Author" = "Tamr"
        }
      + vpc_id                 = (known after apply)
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.ES_access_cidr[0] will be created
  + resource "aws_security_group_rule" "ES_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "Tamr elasticsearch access from allowed CIDR blocks"
      + from_port                = 9200
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 9200
      + type                     = "ingress"
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.UI_access_cidr[0] will be created
  + resource "aws_security_group_rule" "UI_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "Tamr UI and API access from allowed CIDR blocks"
      + from_port                = 9100
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 9100
      + type                     = "ingress"
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.auth_access_cidr[0] will be created
  + resource "aws_security_group_rule" "auth_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "Tamr auth access from allowed CIDR blocks"
      + from_port                = 9020
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 9020
      + type                     = "ingress"
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.grafana_access_cidr[0] will be created
  + resource "aws_security_group_rule" "grafana_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "Grafana port"
      + from_port                = 31101
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 31101
      + type                     = "ingress"
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.http_access_cidr[0] will be created
  + resource "aws_security_group_rule" "http_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "HTTP from allowed CIDR blocks"
      + from_port                = 80
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 80
      + type                     = "ingress"
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.kibana_access_cidr[0] will be created
  + resource "aws_security_group_rule" "kibana_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "Kibana port"
      + from_port                = 5601
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 5601
      + type                     = "ingress"
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.persistence_access_cidr[0] will be created
  + resource "aws_security_group_rule" "persistence_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "Tamr persistence access from allowed CIDR blocks"
      + from_port                = 9080
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 9080
      + type                     = "ingress"
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.ping_access_cidr[0] will be created
  + resource "aws_security_group_rule" "ping_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "Ping from allowed CIDR blocks"
      + from_port                = -1
      + id                       = (known after apply)
      + protocol                 = "icmp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = -1
      + type                     = "ingress"
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.ssh_access_cidr[0] will be created
  + resource "aws_security_group_rule" "ssh_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "SSH from allowed CIDR blocks"
      + from_port                = 22
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 22
      + type                     = "ingress"
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.tls_access_cidr[0] will be created
  + resource "aws_security_group_rule" "tls_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "TLS from allowed CIDR blocks"
      + from_port                = 443
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 443
      + type                     = "ingress"
    }

  # module.tamr-vm.module.aws-security-groups.aws_security_group_rule.zk_access_cidr[0] will be created
  + resource "aws_security_group_rule" "zk_access_cidr" {
      + cidr_blocks              = [
          + "1.2.3.0/24",
        ]
      + description              = "Zookeeper access from allowed CIDR blocks"
      + from_port                = 21281
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 21281
      + type                     = "ingress"
    }

  # module.tamr-vm.module.tamr_instance.data.template_cloudinit_config.bootstrap-scripts[0] will be read during apply
  # (config refers to values not yet known)
 <= data "template_cloudinit_config" "bootstrap-scripts"  {
      + base64_encode = true
      + id            = (known after apply)
      + rendered      = (known after apply)

      + part {
          + content      = (known after apply)
          + content_type = "text/x-shellscript"
        }
      + part {
          + content      = (known after apply)
          + content_type = "text/x-shellscript"
        }
    }

  # module.tamr-vm.module.tamr_instance.data.template_cloudinit_config.bootstrap-scripts[1] will be read during apply
  # (config refers to values not yet known)
 <= data "template_cloudinit_config" "bootstrap-scripts"  {
      + base64_encode = true
      + id            = (known after apply)
      + rendered      = (known after apply)

      + part {
          + content      = (known after apply)
          + content_type = "text/x-shellscript"
        }
      + part {
          + content      = (known after apply)
          + content_type = "text/x-shellscript"
        }
    }

  # module.tamr-vm.module.tamr_instance.aws_instance.tamr-instance will be created
  + resource "aws_instance" "tamr-instance" {
      + ami                          = "foo"
      + arn                          = (known after apply)
      + associate_public_ip_address  = (known after apply)
      + availability_zone            = "us-east-1e"
      + cpu_core_count               = (known after apply)
      + cpu_threads_per_core         = (known after apply)
      + get_password_data            = false
      + host_id                      = (known after apply)
      + iam_instance_profile         = (known after apply)
      + id                           = (known after apply)
      + instance_state               = (known after apply)
      + instance_type                = "m4.2xlarge"
      + ipv6_address_count           = (known after apply)
      + ipv6_addresses               = (known after apply)
      + key_name                     = "tamr-ec2-test-key"
      + outpost_arn                  = (known after apply)
      + password_data                = (known after apply)
      + placement_group              = (known after apply)
      + primary_network_interface_id = (known after apply)
      + private_dns                  = (known after apply)
      + private_ip                   = (known after apply)
      + public_dns                   = (known after apply)
      + public_ip                    = (known after apply)
      + secondary_private_ips        = (known after apply)
      + security_groups              = (known after apply)
      + source_dest_check            = true
      + subnet_id                    = (known after apply)
      + tags                         = {
          + "Author" = "Tamr"
          + "Name"   = "Tamr VM"
        }
      + tenancy                      = (known after apply)
      + user_data                    = (known after apply)
      + vpc_security_group_ids       = (known after apply)

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = true
          + device_name           = (known after apply)
          + encrypted             = true
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = 100
          + volume_type           = "gp2"
        }
    }

Plan: 35 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by daniosim — APPROVED** [review]
👍

**Pull request merged**
