### PR TITLE
DEV-14726 - Add depends on relationship

### PR DESCRIPTION
**Pull request by souza-dan**
https://datatamr.atlassian.net/browse/DEV-14726

Able to reproduce the issue with the policy not attaching by:
1. create the vm, confirm s3 works
2 running taint on all the resources (with the script from the public docs).  
3. run apply, confirm s3 does not work
```
$ echo "hello" > hello.txt
$ aws s3 cp --sse AES256 hello.txt s3://test-hbase-root-directory-bucket/hello-2.txt 
upload failed: ./hello.txt to s3://test-hbase-root-directory-bucket/hello-2.txt Unable to locate credentials
$ aws s3 ls s3://test-hbase-root-directory-bucket/
Unable to locate credentials. You can configure credentials by running "aws configure".
```

After adding the explicit depends on for the ec2 instance on the policies module, running taint/apply the policy attaches correctly:
```
$ echo "hello" > hello.txt
$ aws s3 cp --sse AES256 hello.txt s3://test-hbase-root-directory-bucket/hello-3.txt 
upload: ./hello.txt to s3://test-hbase-root-directory-bucket/hello-3.txt
$ aws s3 ls s3://test-hbase-root-directory-bucket/
                           PRE bootstrap-script-tamr-vm/
2021-04-16 15:28:14          6 hello-2.txt
2021-04-16 15:34:22          6 hello-3.txt
2021-04-16 15:12:29          6 hello.txt
```

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by daniosim — APPROVED** [review]
Looks good!

**Pull request merged**
