### PR TITLE
[CA-32] Add tags to EBS volume and network interface in Tamr VM module

### PR DESCRIPTION
**Pull request by fvazquez-caylent**
To allow for further tightening of IAM permissions, the VM module should allows also tagging EBS root volume and root ENI.

Summary of changes:

* Adds tags to the EC2 instance's root EBS volume
* Adds network interface resource used as the default network interface on the EC2 instance in order to support tags
* Updates source to point to the newer VM repo release which is going to be a major release 4.0.0

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by souza-dan — APPROVED** [review]
LGTM, how disruptive is the upgrade process from the previous version?

**Comment by fvazquez-caylent** [comment]
@souza-dan, thanks for reviewing this PR.
Since the customer would have created the Tamr VM with another version, using Tamr VM relesae 4.0.0 will cause the Tamr VM to be recreated mainly because a new network interface will be created that needs to be assigned as a ` device_index = 0`.
Adding a tag to the ebs root volume will preserve the current instance.

**Comment by souza-dan** [comment]
> @souza-dan, thanks for reviewing this PR.
> Since the customer would have created the Tamr VM with another version, using Tamr VM release 4.0.0 will cause the Tamr VM to be recreated mainly because a new network interface will be created that needs to be assigned as a ` device_index = 0`.
> Adding a tag to the EBS root volume will preserve the current instance.

Got it! Could we include this as a note in the CHANGELOG to guide someone that might be upgrading?

**Comment by fvazquez-caylent** [comment]
> > @souza-dan, thanks for reviewing this PR.
> > Since the customer would have created the Tamr VM with another version, using Tamr VM release 4.0.0 will cause the Tamr VM to be recreated mainly because a new network interface will be created that needs to be assigned as a ` device_index = 0`.
> > Adding a tag to the EBS root volume will preserve the current instance.
> 
> Got it! Could we include this as a note in the CHANGELOG to guide someone that might be upgrading?

Added a note and resubmitted.

**Review by souza-dan — APPROVED** [review]
LGTM, thanks for adding that note!

**Pull request merged**
